// FrontEnd/TypeScript Trucos (LinkedIn Learning)/trucos-type-script/apps/my-angular-app/src/app/app.component.ts
import { Component } from '@angular/core';
import { greet, sum } from '@trucos-type-script/utils';
import { Author } from '@trucos-type-script/models';
@Component({
  selector: 'trucos-type-script-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  title = 'my-angular-app';

  greeting = greet('Yasmin');
  author!: Author;
}

<h1>{{greeting}}, </h1>
<h1>Bienvenido a {{title}}</h1><trucos-type-script-nx-welcome></trucos-type-script-nx-welcome>

// FrontEnd/TypeScript Trucos (LinkedIn Learning)/trucos-type-script/apps/my-react-app/src/app/app.tsx
import styles from './app.module.scss';
import NxWelcome from './nx-welcome';
import {greet} from  '@trucos-type-script/utils';
export function App() {
  
  const greeting = greet("Mr. Yam");
  return (
    <>
    {greeting}
      <NxWelcome title="my-react-app" />
      <div />
    </>
  );
}

export default App;
